version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
          - .:/var/www/html
    environment:
     DSN: "host=db port=5432 user=postgres password=root dbname=players sslmode=disable"

    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: players
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
   
